version: '3.8'
services:
  app:
    container_name: finance-app
    build: .
    ports:
      - "${APP_PORT}:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    driver: local
  elasticsearch-data:
    driver: local
